sudo: false
language: node_js
services:
- couchdb
notifications:
  email: false
node_js:
- '0.12'
# env:
#   matrix:
#   - COUCH_URL=http://localhost:5984/
#   - COUCH_URL=
before_install:
- npm i -g npm@^2.0.0
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
install:
- npm install --no-optional
after_success:
- npm run semantic-release
