sudo: false
language: node_js
services:
- couchdb
notifications:
  email: false
node_js:
- 4
before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
after_success:
- npm run semantic-release
