before_install:
- npm install -g bower grunt-cli
- bower install
language: node_js
node_js:
- '0.10'
notifications:
  irc:
    channels:
    - chat.freenode.net#hoodie
    use_notice: true
    skip_join: true
deploy:
  provider: npm
  email: me@svenlito.com
  api_key:
    secure: bhLkyV8E/BjAQj/yrvY0ZeqwAtOfEKZeEEtL/J6Z7kTwo7P2M8seoyzmYjUYhd4mRfpVXzgyG3yj4BrCAT/VUt78kcs7IGXuM6GcuJBVm98wrMbz7Dw0YxDLNpPRzQ8CuBNOf7mtmc2C3EcB+f+Cii0gYf8ZeKbb7T5sPy1U0u4=
  on:
    tags: true
    repo: hoodiehq/hoodie.js
